### ISSUE TITLE
How to display method name in the consola log

### ISSUE THREAD

**Issue by abhinaba-ghosh** [nuxt-contrib/consola#103]
Hi, I am very new to `consola`. Is there a way to display the method name from where the `console.info` gets called?

**Comment by pi0** [comment]
It is possible using either Reflection or legacy [`Function.caller`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/caller) but since there is no stable way it wasn't implemented.

You may use a named logger with [wthScope](https://github.com/nuxt-contrib/consola#withtagtag) to know source of each log.

**Comment by abhinaba-ghosh** [comment]
Thanks @pi0 ,This should unblock me.
